#!/bin/sh
### BEGIN INIT INFO
# Provides:          aafirstboot
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5 S
# Default-Stop:
# Short-Description: First boot system setup
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin


if [ -f /.first_boot ]; then
	echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
	rm -fr /.first_boot
	sync
	/etc/init.d/S50sshd restart
fi
